create table {tableName}
(
  id                      NUMBER(20) primary key,
  gmt_created             NUMBER(20),
  log_time                NUMBER(20),
  log_type                NVARCHAR2(32),
  success                 NUMBER(1),
  msg                     CLOB,
  code                    NVARCHAR2(32),
  job_type                NVARCHAR2(32),
  task_tracker_identity   NVARCHAR2(64),
  task_id                 NVARCHAR2(64),
  real_task_id            NVARCHAR2(64),
  job_id                  NVARCHAR2(64),
  priority                NUMBER(11),
  submit_node_group       NVARCHAR2(64),
  task_tracker_node_group NVARCHAR2(64),
  ext_params              CLOB,
  internal_ext_params     CLOB,
  need_feedback           NUMBER(4),
  cron_expression         NVARCHAR2(128),
  trigger_time            NUMBER(20),
  retry_times             NUMBER(11),
  max_retry_times         NUMBER(11) default 0,
  rely_on_prev_cycle      NUMBER(4),
  repeat_count            NUMBER(11) default 0,
  repeated_count          NUMBER(11) default 0,
  repeat_interval         NUMBER(20) default 0,
  log_level               NVARCHAR2(32)
)
