create table {tableName}
(
  id                         NUMBER(20) primary key,
  job_id                     NVARCHAR2(32),
  job_type                   NVARCHAR2(32),
  priority                   NUMBER(11),
  retry_times                NUMBER(11) default 0,
  max_retry_times            NUMBER(11) default 0,
  rely_on_prev_cycle         NUMBER(4),
  task_id                    NVARCHAR2(64),
  real_task_id               NVARCHAR2(64),
  gmt_created                NUMBER(20),
  gmt_modified               NUMBER(20),
  submit_node_group          NVARCHAR2(64),
  task_tracker_node_group    NVARCHAR2(64),
  ext_params                 CLOB,
  internal_ext_params        CLOB,
  is_running                 NUMBER(1),
  task_tracker_identity      NVARCHAR2(64),
  need_feedback              NUMBER(4),
  cron_expression            NVARCHAR2(128),
  trigger_time               NUMBER(20),
  repeat_count               NUMBER(11) default 0,
  repeated_count             NUMBER(11) default 0,
  repeat_interval            NUMBER(20) default 0,
  last_generate_trigger_time NUMBER(20) default 0,
  unique (job_id),
  unique (task_id, task_tracker_node_group)
)